name: pms
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  cupertino_icons: ^1.0.8
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: OpenSansEB
      fonts:
        - asset: assets/font/OpenSans-ExtraBold.ttf
        
    - family: OpenSansLight
      fonts:
        - asset: assets/font/OpenSans-Light.ttf

    - family: OpenSansSB
      fonts:
        - asset: assets/font/OpenSans_SemiBold.ttf

  uses-material-design: true

  assets:
    - assets/map/map.PNG
    - assets/map/spc.png
    - assets/icon/shc.png
    - assets/map/placement.PNG
    - assets/map/tiaong.png
    - assets/map/sanpablo.png
    - assets/map/alaminos.png
    - assets/map/rizal.png
    - assets/map/lipa.png
    - assets/map/dolores.png
    - assets/map/calauan.png
    - assets/map/nagcarlan.png